version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"  
    schedule:
      interval: "weekly"  
    open-pull-requests-limit: 5
    assignees:
      - ShyamSundhar1411
    reviewers:
      - ShyamSundhar1411
    commit-message:
      prefix: "chore(deps)"
      include: "scope"